# Generated by Django 5.0.3 on 2024-06-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
